### ISSUE TITLE
numeric as strings? 

### ISSUE THREAD

**Issue by srconklin** [gcanti/tcomb-form#60] opened 2015-01-29 00:29 UTC
I  have a form defined with a hidden field like so 

```
var theForm = t.struct({
      route_id: t.maybe(t.Str),
        });
.....
fields: {
        route_id: {
            type: 'hidden'
  } 
....
```

it s failing validation because the id is numeric..(i think) 
I am using tcombs-from as an edit form that is pulling up data from a db... 
it so happens for this record the id  is "70"  but for other records it might be alpha like so "NJB" 

can i not have numerical data in a string field?

**Comment by gcanti** [comment] 2015-01-29 00:38
> it s failing validation because the id is numeric..(**i think**) 

Try to call `getValue(true)` with the `true` argument: it will return a raw result containing all the validation errors so you can inspect which value is wrong for tcomb-form

**Comment by gcanti** [comment] 2015-01-30 10:47
Can I close this issue?

**Comment by srconklin** [comment] 2015-01-30 13:30
sorry - been slammed with other projects.. i will try to recreate shortly and report back.

**Comment by srconklin** [comment] 2015-01-31 00:38
this is what i get in the dev console window
message::  / is `65` should be a `Str`"
Full dump below:

```
 Struct {errors: Array[1], value: Object, isValid: function, firstError: function, toString: function}errors: Array[1]0: Structactual: 65expected: function Irreducible(value) {arguments: (...)get arguments: function ThrowTypeError() { [native code] }set arguments: function ThrowTypeError() { [native code] }caller: (...)get caller: function ThrowTypeError() { [native code] }set caller: function ThrowTypeError() { [native code] }displayName: "Str"is: function isStr(x) {length: 1meta: Objectname: "Irreducible"prototype: Str__proto__: function Empty() {}<function scope>message: "/ is `65` should be a `Str`"path: Array[0]__proto__: ValidationErrorlength: 1__proto__: Array[0]concat: function concat() { [native code] }constructor: function Array() { [native code] }entries: function entries() { [native code] }every: function every() { [native code] }filter: function filter() { [native code] }forEach: function forEach() { [native code] }indexOf: function indexOf() { [native code] }join: function join() { [native code] }keys: function keys() { [native code] }lastIndexOf: function lastIndexOf() { [native code] }length: 0map: function map() { [native code] }pop: function pop() { [native code] }push: function push() { [native code] }reduce: function reduce() { [native code] }reduceRight: function reduceRight() { [native code] }reverse: function reverse() { [native code] }shift: function shift() { [native code] }slice: function slice() { [native code] }some: function some() { [native code] }sort: function sort() { [native code] }splice: function splice() { [native code] }toLocaleString: function toLocaleString() { [native code] }toString: function toString() { [native code] }unshift: function unshift() { [native code] }Symbol(Symbol.iterator): function ArrayValues() { [native code] }Symbol(Symbol.unscopables): Object__proto__: Objectvalue: Object__proto__: ValidationResult

```

**Comment by gcanti** [comment] 2015-01-31 04:48
It seems that tcomb-form correctly complains that the number `65` is not a string,
Are you sure that you don't feed tcomb-form with that number as value in the first place?

Otherwise it's very strange what happens: could you send me a working snippet that reproduces this issue?

**Comment by srconklin** [comment] 2015-01-31 14:01
>> Are you sure that you don't feed tcomb-form with that number as value in the first place?

yes of course! I am using tcomb-forms as an edit mask not just data input,  The value "65" is was set to the hidden field of the form on the first render and is not visible or editable.
(see screenshot in link below)
 
>> It seems that tcomb-form correctly complains that the number 65 is not a string,
I would disagree. In db systems, it is quite common to define a string where any combination of alphanumeric characters are valid including just a series of numbers. like a U.S. Postal Code: 77025, 77039, 90125 etc..  they are always numbers (integers really) ,but a DB admin would always store this a varchar (string) field, because you really don't perform any mathematical operations against them,.. you  just display them. (and if you ever need to store international postal codes then you could have letters..)

If i specify a form field as T.str  should i not be allowed to enter anything that can be represented as  a string? 

http://www.evernote.com/shard/s349/sh/228c262c-cef8-41f0-af31-06d2bfe25cfc/f143399e3654b4c275d3a84900b0b293

**Comment by gcanti** [comment] 2015-01-31 14:50
> If i specify a form field as T.str should i not be allowed to enter anything that can be represented as a string?

Yes, anything that **is** a string.

From the dump I see you get the error:

```
/ is 65 should be a Str
```

not 

```
 / is "65" should be a Str
 ``

so tcomb-form is validating the **number** `65` (type number: `t.Num`), not the **string** `"65"` (type string: `t.Str`). Hence it complains.

The conjecture in my previous comment was: is it possible that you feed tcomb-form with the (invalid) number `65` instead of the (valid) string `"65"`? In that case, since it's a hidden field and there's not any user interaction, tcomb-form will simply return the original value causing the validation error.

You write 

> route id can be a **number** or a set of characters

so I guess it's a possibility

**Comment by srconklin** [comment] 2015-01-31 15:20
You are correct. sorry,  that escaped me.  I will convert all values to javascript sttrings before passing the object into the value property of the t.form.create method...

Sorry about that.

**Comment by gcanti** [comment] 2015-01-31 15:32
No problem ;-)

**Comment by gcanti** [comment] 2015-01-31 15:43
> I will convert all values..

Oh..if you want to avoid conversions, another fix would be to define the field as a `t.Any`

```js
var theForm = t.struct({
  route_id: t.Any, // handles any type: strings, numbers, ...
});
```

you lose type checking on that field but since it's hidden and it's in your complete control I think it wouldn't be much of a problem. This way if you feed tcomb-form with numbers you'll get numbers, if you feed tcomb-form with strings you'll get strings.

**Comment by srconklin** [comment] 2015-01-31 17:06
thank you. I did not know about any... guess i should read the documentation better

**Closed** 2015-02-02 06:14 UTC
